version: 2
updates:
  - package-ecosystem: bun
    directory: /
    schedule:
      interval: monthly
  - package-ecosystem: bun
    directory: /picker
    schedule:
      interval: monthly
  - package-ecosystem: cargo
    directory: /picker/src-tauri
    schedule:
      interval: monthly
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
